name: Android

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: add rust target
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - name: build
        run: ./gradlew :MaskWalletCore:build
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew :MaskWalletCore:connectedCheck

